version: "3.9"

services:
  backend:
    build: ./backend
    container_name: zeroapi_backend
    command: bash entrypoint.sh
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    container_name: zeroapi_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: zeroapi_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis:7
    container_name: zeroapi_redis
    ports:
      - "6379:6379"

  celery_worker:
    build: ./backend
    container_name: zeroapi_celery
    command: celery -A zeroapi worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
    env_file:
      - .env

volumes:
  pgdata:

